version: '3.4'

volumes:
  identity_data:
    external: true
  booking_data:
    external: true
  room_data:
    external: true

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    hostname: rabbitmqserver
    environment:
      - RABBITMQ_DEFAULT_USER=RabbitMqUser
      - RABBITMQ_DEFAULT_PASS=RabbitMqPassword
    ports:
      # AMQP protocol port
      - '5500:5672'
      # HTTP management UI
      - '5510:15672'

  bookingdbserver:
    image: mysql:8.0.30
    container_name: bookingsdbserver
    command:
      --innodb_buffer_pool_size=5M 
      --innodb_log_buffer_size=256K
      --max_connections=10 
      --key_buffer_size=8 
      --thread_cache_size=0 
      --host_cache_size=0 
      --innodb_ft_cache_size=1600000 
      --innodb_ft_total_cache_size=32000000 
      --thread_stack=131072 
      --sort_buffer_size=32K 
      --read_buffer_size=8200 
      --read_rnd_buffer_size=8200 
      --max_heap_table_size=16K 
      --tmp_table_size=1K 
      --bulk_insert_buffer_size=0 
      --join_buffer_size=128 
      --net_buffer_length=1K 
      --innodb_sort_buffer_size=64K 
      --binlog_cache_size=4K 
      --binlog_stmt_cache_size=4K 
      --performance_schema=off
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.bookingsdb
    ports:
      - 5210:3306
    volumes:
      - booking_data:/var/lib/mysql

  roomdbserver:
    image: mysql:8.0.30
    container_name: roomsdbserver
    command: 
      --innodb_buffer_pool_size=5M 
      --innodb_log_buffer_size=256K
      --max_connections=10 
      --key_buffer_size=8 
      --thread_cache_size=0 
      --host_cache_size=0 
      --innodb_ft_cache_size=1600000 
      --innodb_ft_total_cache_size=32000000 
      --thread_stack=131072 
      --sort_buffer_size=32K 
      --read_buffer_size=8200 
      --read_rnd_buffer_size=8200 
      --max_heap_table_size=16K 
      --tmp_table_size=1K 
      --bulk_insert_buffer_size=0 
      --join_buffer_size=128 
      --net_buffer_length=1K 
      --innodb_sort_buffer_size=64K 
      --binlog_cache_size=4K 
      --binlog_stmt_cache_size=4K 
      --performance_schema=off
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.roomsdb
    ports:
      - 5310:3306
    volumes:
      - room_data:/var/lib/mysql

  identitydbserver:
    image: mysql:8.0.30
    container_name: identitydbserver
    command: 
      --innodb_buffer_pool_size=5M 
      --innodb_log_buffer_size=256K
      --max_connections=10 
      --key_buffer_size=8 
      --thread_cache_size=0 
      --host_cache_size=0 
      --innodb_ft_cache_size=1600000 
      --innodb_ft_total_cache_size=32000000 
      --thread_stack=131072 
      --sort_buffer_size=32K 
      --read_buffer_size=8200 
      --read_rnd_buffer_size=8200 
      --max_heap_table_size=16K 
      --tmp_table_size=1K 
      --bulk_insert_buffer_size=0 
      --join_buffer_size=128 
      --net_buffer_length=1K 
      --innodb_sort_buffer_size=64K 
      --binlog_cache_size=4K 
      --binlog_stmt_cache_size=4K 
      --performance_schema=off
    environment:
      - MYSQL_ROOT_PASSWORD=mysq1DbP@ss
      - MYSQL_DATABASE=mra.identitydb
    ports:
      - 5010:3306
    volumes:
      - identity_data:/var/lib/mysql

  identity.api:
    container_name: identity
    image: ${DOCKER_REGISTRY-}identity
    build: ../src/Services/Identity/Identity.API
    ports:
      - 5000:80
    depends_on:
      - identitydbserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  gateway.api:
    container_name: gateway
    image: ${DOCKER_REGISTRY-}gateway
    build: ../src/Services/Gateway/Gateway.API
    ports:
      - 5100:80
    depends_on:
      - rabbitmq
      - signalr.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  user.api:
    container_name: users
    image: ${DOCKER_REGISTRY-}users
    build: ../src/Services/Users/User.API
    ports:
      - 5020:80
    depends_on:
      - identitydbserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  room.api:
    container_name: rooms
    image: ${DOCKER_REGISTRY-}rooms
    build: ../src/Services/Rooms/Room.API
    ports:
      - 5300:80
    depends_on:
        - roomdbserver
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  booking.api:
    container_name: bookings
    image: ${DOCKER_REGISTRY-}bookings
    build: ../src/Services/Bookings/Booking.API
    ports:
      - 5200:80
    depends_on:
      - rabbitmq
      - signalr.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  signalr.api:
    container_name: signalr
    image: ${DOCKER_REGISTRY-}signalr
    build: ../src/Services/SignalR/SignalR.API
    ports:
      - 5400:80
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker

  angular.spa:
    container_name: spa
    image: ${DOCKER_REGISTRY-}angular
    build: ../src/Clients/Angular.SPA
    ports:
      - 4200:80
    depends_on:
      - rabbitmq
      - signalr.api
    environment:
      - ASPNETCORE_ENVIRONMENT=Docker